### ISSUE TITLE
hello there, is there any way i can get printer history records?

### ISSUE THREAD

**Issue by Davidzhu001** [ZebraDevs/Zebra-Printer-Samples#4]
hello there, is there any way i can get printer history records?

**Comment by ssizebra** [comment]
What type of history records do you want to see? By default, the history tracking is off. By design, it is intended to be off, because of its memory usage. It can be enabled for debugging purpose.
! U1 getvar "input.capture"           /* Check tracking */
! U1 setvar "input.capture" "run"  /* Turn on tracking */
! U1 setvar "input.capture" "off"   /* Turn off tracking */

The input capture is stored in INxxx.DMP files. Check the ZPL Users Manual for the Input Capture.

**Comment by Davidzhu001** [comment]
ok @ssizebra thanks. my case is my company want to record each print from users, can i restore it and clean the memory for GK888T?

**Comment by ssizebra** [comment]
You could. But it's not practical, as you will have to track when it's time to remove the *.DMP files to clear the space on the flash.

**Comment by Davidzhu001** [comment]
thanks a lot @ssizebra

**Comment by Davidzhu001** [comment]
if i use usb port for print and ethernet for watch *.DMP files, will this way wokr?

**Comment by ssizebra** [comment]
Even though Link-OS SDK a and TCP connection open at the same time, the printer can only process one request at a time. It's not prudent to use TCP to download the *.DMP while using USB to send ZPL. Because the data to the printer will probably get mingled at the the printer and cause the corruption. So, it's not recommend to use both connections at the same time.
